export const ADD_ITEM_IN_TODOS = 'ADD_ITEM_IN_TODOS';
export const DELETE_ITEM_IN_TODOS = 'DELETE_ITEM_IN_TODOS';
export const UPDATE_IS_COMPLETED_ALL_TODO = 'UPDATE_IS_COMPLETED_ALL_TODO';
export const UPDATE_ITEM_IN_TODOS = 'UPDATE_ITEM_IN_TODOS';
export const DELETE_ALL_TODO_COMPLETED = 'DELETE_ALL_TODO_COMPLETED';

export const UPDATE_FILTER_MODE_CURRENT = 'UPDATE_FILTER_MODE_CURRENT';
